// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDICllD8r7StQlBf2s-iukz6IHbS10M4rk',
    appId: '1:646109710642:web:807e99d37357488ea12f2b',
    messagingSenderId: '646109710642',
    projectId: 'foresight-investment-tracker',
    authDomain: 'foresight-investment-tracker.firebaseapp.com',
    storageBucket: 'foresight-investment-tracker.appspot.com',
    measurementId: 'G-VM1CJZJ19V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXECzqpIaROO-njW1xnGFQHZ4X9Go_qTc',
    appId: '1:646109710642:android:680667dee4198667a12f2b',
    messagingSenderId: '646109710642',
    projectId: 'foresight-investment-tracker',
    storageBucket: 'foresight-investment-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEANEpY6sGuPp_dZpCcyJBP0QzYYM3sD4',
    appId: '1:646109710642:ios:96ca575f4421171ca12f2b',
    messagingSenderId: '646109710642',
    projectId: 'foresight-investment-tracker',
    storageBucket: 'foresight-investment-tracker.appspot.com',
    iosClientId: '646109710642-a3uo48q9411kt9i4aqmhqoef45ts81uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.foresight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEANEpY6sGuPp_dZpCcyJBP0QzYYM3sD4',
    appId: '1:646109710642:ios:96ca575f4421171ca12f2b',
    messagingSenderId: '646109710642',
    projectId: 'foresight-investment-tracker',
    storageBucket: 'foresight-investment-tracker.appspot.com',
    iosClientId: '646109710642-a3uo48q9411kt9i4aqmhqoef45ts81uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.foresight',
  );
}
